### ISSUE TITLE
Recover from failures

### ISSUE THREAD

**Issue by jugglinmike** [davidchambers/xyz#16]
If the script fails, it should roll back any changes it has already made to the local and remote repositories.

Alternatively, the script could defensively check for more capabilities prior to making any changes. This would include:
- User has push access to remote repository
- Release tag does not exist on local and remote repositories
- User is logged in to npm and has package publication rights

**Comment by davidchambers** [comment]
I'll close this issue as it's not directly actionable. Pull requests for such improvements are welcome. :)
