### ISSUE TITLE
atomic `git push`

### ISSUE THREAD

**Issue by davidchambers** [davidchambers/xyz#18]
Currently, we push via:

```bash
run "git push '$repo' 'refs/heads/$branch' 'refs/tags/$tag'"
```

This is not an atomic operation, apparently. If one is not up to date with `$branch`, the branch push will fail but the tag push will succeed. This results in the tagged commit not living on `$branch` (or any other branch).

Perhaps we should do this instead:

```bash
run "git push '$repo' 'refs/heads/$branch'"
run "git push '$repo' 'refs/tags/$tag'"
```

This won't help if the *tag* already exists, though this is less likely.

Perhaps `git push` provides an `--atomic` or `--transaction` flag. This would be ideal.

**Comment by michaelficarra** [comment]
How about this?

```bash
run "git push '$repo' 'refs/heads/$branch' --follow-tags"
```

**Comment by davidchambers** [comment]
`--follow-tags` seems perfect!

>        --follow-tags
>            Push all the refs that would be pushed without this option,
>            and also push annotated tags in refs/tags that are missing
>            from the remote but are pointing at commit-ish that are
>            reachable from the refs being pushed.

I assume the tags aren't pushed if the branch push fails. I'll verify this assumption.

**Comment by michaelficarra** [comment]
It's what I typically use when manually bumping versions.

**Comment by davidchambers** [comment]
> I assume the tags aren't pushed if the branch push fails. I'll verify this assumption.

I wrote a test which revealed this to be a false assumption. `--follow-tags` pushes the tags blindly.

I've posted a [question][1] in the hopes of discovering an ideal solution. I suspect we'll end up pushing the branch and the tag in separate `git push` operations.


[1]: http://superuser.com/q/900837/176942

**Comment by LinusU** [comment]
@davidchambers The question seems to have been removed, did you ever manage to solve this?

**Comment by davidchambers** [comment]
The question was deleted for being "abandoned", though I'd consider it "unanswered" or "unsolved" rather than abandoned. Here it is in full:

> __atomic `git push`: don't push tag if branch push fails__
>
> I'd like to solve [davidchambers/xyz#18][1]. Assuming I have a tagged commit which I'd like to push to a remote repository, this *usually* works:
>
>     git push "$repo" "refs/heads/$branch" "refs/tags/$tag"
>
> A problem arises if the local `$branch` and remote `$branch` have diverged. The branch push will fail but the tag push will succeed. This remote will then have the tagged commit but it won't live on any branch.
>
> Instead, I'd like the tag to be pushed only if the branch push succeeds. In fact, I'd like the pushes to be treated as a transaction such that both operations fail unless both operations succeed. Is this possible? The `--follow-tags` flag does not cause the tag(s) to be pushed conditionally.

It seems there is currently no way to perform these two operations as a transaction. We can at least perform two `git push` operations to control order. Another option is to query the remote repository before pushing, but this would introduce a race condition.

p.s. I'm sorry for taking three weeks to respond, @LinusU!


[1]: https://github.com/davidchambers/xyz/issues/18

**Comment by LinusU** [comment]
I managed to solve this by using the `--atomic` flag, unfortunately it doesn't work with the `--follow-tags` flag so you have to specify the branch and tag manually.

```sh
git push --atomic "$repo" "refs/heads/$branch" "refs/tags/$tag"
```

example: pinn3/release-package#3

**Comment by davidchambers** [comment]
> I managed to solve this by using the `--atomic` flag

Wait, what?! I had no idea that such a flag exists. It turns out it was [added][1] two months before I opened this issue (though it's unlikely my Git version at the time included it).

Anyway, this is *excellent* news. :)

```console
$ git push --help | grep --after-context=3 -- '--\[no-\]atomic'
       --[no-]atomic
           Use an atomic transaction on the remote side if available. Either
           all refs are updated, or on error, no refs are updated. If the
           server does not support atomic pushes the push will fail.
```

> unfortunately [the `--atomic` flag] doesn't work with the `--follow-tags` flag so you have to specify the branch and tag manually

That's no problem at all. We're currently specifying the branch and tag:

> ```bash
> run "git push '$repo' 'refs/heads/$branch' 'refs/tags/$tag'"
> ```

Thanks for bringing this flag to my attention, @LinusU. Would you like to submit a pull request? I'm happy to do so myself, but you deserve the credit. :)


[1]: https://github.com/git/git/commit/39fa6112ec8492f9300765e1f71e7c8ecfafc713

**Comment by LinusU** [comment]
I'd be happy to, see #22 :)

**Comment by davidchambers** [comment]
Excellent. Thank you!
