### ISSUE TITLE
Document additional flags in README

### ISSUE THREAD

**Issue by albrow** [davidchambers/xyz#20]
When viewing the page for [xyz on npm](https://www.npmjs.com/package/xyz) or looking at the README, there isn't much documentation about the different flags that are supported. I recognize that there are extensive comments in the source code explaining the different flags, and there is excellent support for a `--help` flag in the `xyz` command itself. However, it would be great if that information was more readily available.

I happen to know of a great tool called [Transcribe](https://github.com/plaid/transcribe) that might be useful for adding the documentation to the README ;)

**Comment by davidchambers** [comment]
I agree that the `--help` output should be included in the readme in some form. :thumbsup:
