### ISSUE TITLE
Consider using npm version internally

### ISSUE THREAD

**Issue by jgrund** [davidchambers/xyz#21]
If we use `npm version` to bump the version the user could use lifecycle hooks in their `package.json` (`preversion`, `version`, `postversion`).

**Comment by davidchambers** [comment]
Thanks for the suggestion, @jgrund. Could you provide an example of something you'd like to do via `preversion` or `postversion`?

**Comment by jgrund** [comment]
One example is to transpile some ES6 (2015) code to ES5 before publishing a new version.

**Comment by davidchambers** [comment]
Are you aware of the `--script` option?

```console
$ node_modules/.bin/xyz --help | grep --after-context 3 -- --script
-s --script <path>
        Specify a script to be run after the confirmation prompt.
        It is passed VERSION and PREVIOUS_VERSION as environment
        variables. xyz aborts if the script's exit code is not 0.
```

**Comment by jgrund** [comment]
@davidchambers yes. It just seems like using npm for this is an idiomatic way to approach this problem.

In other words we can utilize the existing lifecycle hooks for this and rely on npm for both the implementation of `npm version` and associated lifecycle hooks.

**Comment by davidchambers** [comment]
I agree that using `npm version` would be idiomatic. Two things concern me:

  - increased implementation complexity; and
  - reduced control.

The current implementation is straightforward. Sans the `--help` text it's 100 lines of Bash. The [source][1] for `npm version` is more involved.

Relying on `npm version` would increase our dependence on specific npm behaviour. Currently we run `npm prune`, `npm test`, and `npm publish`. Presumably these will continue to function as they do now. Given the complex behaviour of [`npm version`][2], though, I expect behaviour changes in future releases.

It's also worth noting that this would be a breaking change (unless we were to support both "hooks").

Finally, I would be nervous about making such a change at this point. xyz has scarcely been touched in the last year, which gives me a great deal of confidence as I know I've used it hundreds of times during this period without incident.

I do see the appeal of using `npm version`, as we currently duplicate much of its functionality, but I lean towards continuing to define the steps explicitly. Currently one can see exactly what will happen and in what order by reading xyz's [source][3].

I'm open to having my mind changed, but at this point I'm not in favour of making this change.


[1]: https://github.com/npm/npm/blob/v3.8.3/lib/version.js
[2]: https://docs.npmjs.com/cli/version
[3]: https://github.com/davidchambers/xyz/blob/v0.5.0/xyz

**Comment by jgrund** [comment]
Fair enough. I can see your viewpoint of staying with code that has worked without issue. 

In my case, I like both using `npm preversion` (for flexibility) and how you annotate your tags so they show up nicely in github.

I won't argue this more as I can do what is needed with a few lines of bash.

**Comment by davidchambers** [comment]
> In my case, I like both using `npm preversion` (for flexibility) and how you annotate your tags so they show up nicely in github.

Does `npm version` not create an annotated tag? It [appears][1] to do so:

> ```javascript
>   var flag = sign ? '-sm' : '-am'
> ```


[1]: https://github.com/npm/npm/blob/v3.8.3/lib/version.js#L261

**Comment by jgrund** [comment]
Indeed it does, it also commits the changes, so in fact npm version and xyz are very much overlapping.

**Comment by davidchambers** [comment]
`npm version` might satisfy your needs, in that case. :)
