### ISSUE TITLE
Option not to publish

### ISSUE THREAD

**Issue by Avaq** [davidchambers/xyz#28]
I like to work on closed-source projects as similarly as I can to open-source projects to improve quality. Maintaining a version number is part if my everyday workflow. If I were to integrate `xyz` into my workflow I would like to use it for closed-source projects as well, and the `npm publish`  command at the end stops me from doing so. Would it be acceptable to add some kind of `--no-publish` option to `xyz`?

**Comment by davidchambers** [comment]
> Would it be acceptable to add some kind of `--no-publish` option to `xyz`?

It would be acceptable, certainly, but I think we can do better. :)

I had hoped that simply setting `"private": false` in __package.json__ would suffice, but `npm publish` fails when one attempts to publish a "private" package. What we could do, though, is ensure that the package is not private before running `npm publish`:

```diff
-run "npm publish"
+node -e 'process.exit(require("./package.json").private === true ? 1 : 0)' && run "npm publish"
```

**Comment by Avaq** [comment]
That's a great idea @davidchambers! Want me to create the PR?

**Comment by Avaq** [comment]
:information_source: Working on it.
