### ISSUE TITLE
run command other than `npm publish`

### ISSUE THREAD

**Issue by kedashoe** [davidchambers/xyz#35]
[This](https://github.com/npm/npm/issues/5673) is a problem for me. I wrote a script to move some files to a temp directory and publish that. What do you think about an option to run an arbitrary command rather than `npm publish` at the end of xyz?

**Comment by davidchambers** [comment]
I'm open to this idea. Flexibility would be useful here. I once had to create a dummy `npm` executable and provide a modified `PATH` to `xyz` in order to make `npm publish` a no-op.

Before we continue, could you share the command you'd actually like to run in this case? Is it simply a matter of providing options to `npm publish`?

**Comment by kedashoe** [comment]
> Before we continue, could you share the command you'd actually like to run in this case? Is it simply a matter of providing options to npm publish?

Sort of? I'm running a script, at the end of that script I call `npm publish` with a positional argument. Maybe this could be accomplished by using the current `--script` option to xyz with the added capability of calling `npm publish` with additional arguments at the end. Even if that would work, it feels more complicated to me, ie it seems like it would be simpler if xyz allowed me to specify an arbitrary command to publish, but this is my first time publishing anything on npm so I can't say with great confidence what would be best.

(This is for the hindley-milner parser, which I finally got around to publishing. You can see the script here: https://github.com/kedashoe/hindley-milner-parser-js/blob/master/bin/publish.sh)

**Comment by davidchambers** [comment]
Okay. Please submit a pull request. We should be able to replace `run "npm publish"` with `run "$publish_command"` and add a `--publish-command` option with a default value of `npm publish`.

I'm pleased to see you're working on your parser. :)
