### ISSUE TITLE
respect --publish-command for private packages

### ISSUE THREAD

**Issue by davidchambers** [davidchambers/xyz#37]
In #29 we made this change:

```diff
-run "npm publish"
+node -e 'process.exit(require("./package.json").private === true ? 1 : 0)' && run "npm publish"
```

This allowed xyz to be used for private packages, which is great!

In #36 we made this change:

```diff
-node -e 'process.exit(require("./package.json").private === true ? 1 : 0)' && run "npm publish"
+node -e 'process.exit(require("./package.json").private === true ? 1 : 0)' && run "$publish_command"
```

This allowed an arbitrary command to be run in place of `npm publish`.

We missed an opportunity for simplification in #36. Now that we support `--publish-command` one could specify a no-op such as `--publish-command true`, obviating the need for conditional logic.

Removing the `require("./package.json").private` check would be a breaking change: Aldwin and others would need to add `--publish-command true` to their `xyz` commands. There are valid uses for `--publish-command` for *private* packages. Currently I'm working on a [chat bot][1]. I'll be publishing it via Docker, so I see no reason to publish it via npm as well. Thus I've set `private: true` in __package.json__ simply because publishing to npm is unnecessary. I would, though, like to use `--publish-command` to publish to Docker Hub:

```console
$ xyz --publish-command 'docker push "sanctuary-js/silly-goat:v$VERSION"' ...
```

The above also requires the `--publish-command` to have access to `VERSION` and `PREVIOUS_VERSION`. This seems like a good idea regardless of whether we decide to remove the `private` check.

[1]: https://github.com/sanctuary-js/silly-goat

**Comment by Avaq** [comment]
How about just exiting the script with a successful exit code if everything when well?

```diff
- xyz --publish-command 'docker push "sanctuary-js/silly-goat:v$VERSION"'
+ xyz && docker push "sanctuary-js/silly-goat:v$VERSION"
```

**Comment by Avaq** [comment]
Or maybe a combination of both:

```diff
-node -e 'process.exit(require("./package.json").private === true ? 1 : 0)' && run "$publish_command"
+publish && node -e 'process.exit(require("./package.json").private === true ? 1 : 0)' && run "npm publish"
```

So that by default, it will just run `npm publish` if the package is public, but you might customize it via:

```sh
xyz --no-publish && docker push "sanctuary-js/silly-goat:v$VERSION"
```

**Comment by davidchambers** [comment]
> ```
> $ xyz && docker push "sanctuary-js/silly-goat:v$VERSION"
> ```

`VERSION` is determined by `xyz` and is only available within that process. I don't want `xyz` to modify the shell. We'd need something like this instead:

```console
$ xyz && docker push "sanctuary-js/silly-goat:v$(node --print 'require("./package.json").version')"
```

It seems a shame to have to fetch the version from __package.json__ when we had it on hand just moments earlier.

Now that we support `--publish-command` it doesn't seem correct to look at the `private` field in __package.json__. This field specifies whether the package should be published to the *npm* registry. The fact that I want to prevent a package from being published to the npm registry does not imply that I *also* want to prevent it from being published to Docker Hub, for example.

We *could* continue to perform the `private` check if `--publish-command` is `'npm publish'`.

**Comment by Avaq** [comment]
> `VERSION` is determined by `xyz`

Something I hadn't considered.

> We *could* continue to perform the `private` check

I suppose it's not that important if we're to support `--publish-command`.
